spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a123456.
    url: jdbc:mysql://localhost:3306/meeting_t3?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
  jpa:
    hibernate:
      ddl-auto: validate
      database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

example:
  property: "I AM A DEFAULT PROPERTY OVERRIDE(in github)"